version: '3.3'

services:

  insacoin-core:
    image: gnut3ll4/insacoin:0.10-headless 
    build: insacoin-headless
    volumes:
      - "~/.insacoin:/root/.insacoin"
    ports:
      - 7332:7332
      - 7333:7333
      - 17332:17332
      - 17333:17333
      - 19444:19444
    command: insacoind -txindex -server=1 -rpcallowip=172.0.0.0/8

  insacoin-explorer:
    image: gnut3ll4/insacoin-explorer:latest
    build: insacoin-explorer
    environment:
      - IPSTACK_API_KEY=_change_me_
      - RPC_HOST=insacoin-core
    volumes:
      - "~/.insacoin/insacoin.conf:/insacoin.conf:ro"
    ports:
      - 3002:3002
    depends_on:
      - insacoin-core

  notebook:
    image: jupyter/minimal-notebook
    volumes:
      - "./jupyter/requirements.txt:/requirements.txt"
      - "./jupyter/entrypoint.sh:/entrypoint.sh"
      - "./jupyter/data:/home/jovyan/work"
      - "~/.insacoin/insacoin.conf:/home/jovyan/.insacoin/insacoin.conf:ro"
    ports:
      - 8888:8888
    entrypoint: ["/entrypoint.sh"]
    command: ["start-notebook.sh"]
    
